name: MineBackup
main: alexoft.Minebackup.MineBackup
authors: [ThisIsAreku,ltguide]
version: 0.4.8.4
description: Automatically backup your worlds
commands:
    minebackup:
        description: Manually start backup process
        aliases: [mbck,backup]
        usage: /mbck
permissions:
    minebackup.*:
        description: Allows all command functionality
        children:
             minebackup.manual: true
    minebackup.manual:
        description: Allows you to manually start backup process
        default: op
